accounts/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.home, name="account_home"),
    path('registration/', views.registration, name="registration"),
    path('login/', views.login_view, name = "login_view")
]

myapp/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('home/', views.home_page, name="home_page"),
    path('home/<int:pk>', views.delete_em, name="delete_em"),
    path('home/<int:pk>/update', views.update_emp, name="update_emp"),
    path('emp/add/', views.add_emp,name="add_emp")
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render, HttpResponse

def initial_load(request):
    return HttpResponse("This is Initial Load")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', initial_load),
    path('app/', include("myapp.urls")),
    path('account/', include("accounts.urls"))
]

accounts/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.
class Employee(models.Model):
    name = models.CharField(max_length=200)
    address = models.TextField()
    phone = models.CharField(max_length=14)
    salary = models.CharField(max_length=30)
    designation = models.CharField(max_length=100)
    short_description = models.TextField()
    
    def save(self, *args, **kwargs):
        if self.pk:
            original = Employee.objects.get(pk=self.pk)
            if original.salary != self.salary:
                raise ValidationError("Salary cannot be changed once set.")
            if original.designation != self.designation:
                raise ValidationError("Salary cannot be changed once set.")
            
        super().save(*args, **kwargs)

    

myapp/forms.py
from django import forms
from .models import Employee

class UpdateForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name', 'address', 'phone', 'short_description']

class AddEmployee(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name', 'address', 'phone', 'salary', 'designation', 'short_description']
        widgets = {
            'address': forms.Textarea(attrs={'rows': 3, 'cols': 40}),
            'short_description': forms.Textarea(attrs={'rows': 3, 'cols': 40}),
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login
from myapp.models import Employee
# Create your views here.
def home(request):
    employes = Employee.objects.all()
    return render(request, "accounts/home.html", {"employes": employes})

def registration(request):
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("registration")
    else:
        form = UserCreationForm()
    context = {
        "form": form
    }
    return render(request, "accounts/registration.html", context)

def login_view(request):
    employes = Employee.objects.all()
    emp = {}
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            for employee in employes:
                if user == employee.name:
                    user = user
                    emp = employee
                    break
            login(request, user)
            return redirect("account_home")
    else:
        form = AuthenticationForm()
        
    context = {
        "form": form
    }
    return render(request, "accounts/login.html", context)
    

myapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Employee
from .forms import UpdateForm, AddEmployee

# Create your views here.
def home_page(request):
    employes = Employee.objects.all()
    return render(request, "index.html", {"employes": employes})

def delete_em(request, pk):
    employes = Employee.objects.get(pk=pk)
    employes.delete()
    return redirect("home_page")

def update_emp(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    
    if request.method == 'POST':
        form = UpdateForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            return redirect('home_page')
    else:
        form = UpdateForm(instance=employee)

    return render(request, 'update_emp.html', {'form': form})

def add_emp(request):
    if request.method == 'POST':
        form = AddEmployee(request.POST)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.salary = form.cleaned_data['salary']
            employee.designation = form.cleaned_data['designation']
            employee.save()
            return redirect('home_page')
    else:
        form = AddEmployee()

    return render(request, 'add_emp.html', {'form': form})

accounts/templates/accounts/home.html
{%extends "layout.html"%}

{%block account_home%}
{{request.user}}
<div>
    {%for employee in employes%}
        {% if employee.name == request.user %}
        <p>xx{{employee.name}}</p>
        {%else%}
        <p>aaaaaa</p>
        {% endif %}
    {% endfor %}
</div>
{%endblock%}

accounts/templates/accounts/login.html
{%extends "layout.html"%}

{%block login%}
   <h2>Registration</h2>
   <form method="post" class="bg-secondary text-white pe-auto">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Login</button>
   </form>
{%endblock%}

{%block title%}
Login
{%endblock%}

accounts/templates/accounts/registration.html
{%extends "layout.html"%}

{%block reg%}
   <h2>Registration</h2>
   <form method="post" class="bg-secondary text-white pe-auto">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Registration</button>
   </form>
{%endblock%}

{%block title%}
Register
{%endblock%}

myapp/templates/add_emp.html
{%extends "layout.html"%}

{%block add_emp%}
<h2 class="text-center mt-5">Add Employee</h2>

<form method="post" class="form p-5 mx-5">
    {% csrf_token %}
    {{ form.non_field_errors }}

    <div class="mb-3">
        {{ form.name.label_tag }}
        <input type="text" name="name" id="id_name" class="form-control">
        {{ form.name.errors }}
    </div>

    <div class="mb-3">
        {{ form.address.label_tag }}
        <textarea name="address" id="id_address" rows="3" cols="40" class="form-control"></textarea>
        {{ form.address.errors }}
    </div>

    <div class="mb-3">
        {{ form.phone.label_tag }}
        <input type="text" name="phone" id="id_phone" class="form-control">
        {{ form.phone.errors }}
    </div>

    <div class="mb-3">
        {{ form.salary.label_tag }}
        <input type="text" name="salary" id="id_salary" class="form-control">
        {{ form.phone.errors }}
    </div>

    <div class="mb-3">
        {{ form.designation.label_tag }}
        <input type="text" name="designation" id="id_designation" class="form-control">
        {{ form.phone.errors }}
    </div>

    <div class="mb-3">
        {{ form.short_description.label_tag }}
        <textarea name="short_description" id="id_short_description" rows="3" cols="40" class="form-control"></textarea>
        {{ form.short_description.errors }}
    </div>

    <button type="submit" class="btn btn-primary">Save Employee</button>
</form>

{%endblock%}

{%block title%}
Add Employee
{%endblock%}

myapp/templates/index.html
{%extends "layout.html"%}

{%block nav%}
<nav class="navbar navbar-expand-lg bg-primary-subtle">
  {%include "partials/nav.html"%}
</nav>
{%endblock%}

{%block allemployes%}
      {%for employee in employes%}
      <div class="card m-2" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{employee.name}}</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">{{employee.designation}}</h6>
          <p class="card-text">{{employee.short_description}}</p>

          <!-- Delete & Update -->
          <a href="{%url "update_emp" employee.pk%}" class="card-link text-success-subtle bolder text-decoration-none">Update</a>
          <a href="{%url "delete_em" employee.pk%}" class="card-link text-danger bolder text-decoration-none">Delete</a>
        </div>
      </div>
      {%endfor%}
{%endblock%}

{%block title%}
Home page
{%endblock%}

myapp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%} Home {%endblock%}</title>
    <link rel="stylesheet" href="https://matcha.mizu.sh/matcha.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    {%block nav%}
    {%endblock%}
    <div class="row">
        {%block allemployes%}
        {%endblock%}
    </div>
    {%block update_emp%}
    {%endblock%}

    {%block add_emp%}
    {%endblock%}

    {%block reg%}
    {%endblock%}

    {%block account_home%}
    {%endblock%}

    {%block login%}
    {%endblock%}
</body>
</body>
</html>

myapp/templates/partials/nav.html
<div class="container-fluid">
    <a class="navbar-brand" href="#">Logo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url "add_emp"%}">Add Employee</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Update/Delete Employee</a>
            </li>
            <li class="nav-item">
                <a href="{%url "registration"%}" class="nav-link">Register</a>
            </li>
            <li class="nav-item">
                <a href="{%url "login_view"%}" class="nav-link">Login</a>
            </li>

        </ul>
    </div>
</div>

myapp/templates/update_emp.html
{%extends "layout.html"%}

{%block update_emp%}
<h2 class="text-center mt-5">Update Your Details</h2>
<form method="post" class="form p-5 mx-5">
    {% csrf_token %}
    {{ form.non_field_errors }}

    <div class="mb-3">
        {{ form.name.label_tag }}
        <input type="text" name="name" id="id_name" class="form-control" value="{{ form.name.value }}">
        {{ form.name.errors }}
    </div>

    <div class="mb-3">
        {{ form.address.label_tag }}
        <input type="text" name="address" id="id_address" class="form-control" value="{{ form.address.value }}">
        {{ form.address.errors }}
    </div>

    <div class="mb-3">
        {{ form.phone.label_tag }}
        <input type="text" name="phone" id="id_phone" class="form-control" value="{{ form.phone.value }}">
        {{ form.phone.errors }}
    </div>

    <div class="mb-3">
        {{ form.short_description.label_tag }}
        <textarea name="short_description" id="id_short_description" class="form-control" rows="3" cols="40">{{ form.short_description.value }}</textarea>
        {{ form.short_description.errors }}
    </div>

    <button type="submit" class="btn btn-primary">Update Task</button>
</form>
{%endblock%}

{%block title%}
Update
{%endblock%}